// Code generated by 'go generate'; DO NOT EDIT.

package etw

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modadvapi32 = windows.NewLazySystemDLL("advapi32.dll")
	modtdh      = windows.NewLazySystemDLL("tdh.dll")

	procControlTraceW                          = modadvapi32.NewProc("ControlTraceW")
	procEnableTraceEx2                         = modadvapi32.NewProc("EnableTraceEx2")
	procProcessTrace                           = modadvapi32.NewProc("ProcessTrace")
	procStartTraceW                            = modadvapi32.NewProc("StartTraceW")
	procTraceQueryInformation                  = modadvapi32.NewProc("TraceQueryInformation")
	procTraceSetInformation                    = modadvapi32.NewProc("TraceSetInformation")
	procTdhAggregatePayloadFilters             = modtdh.NewProc("TdhAggregatePayloadFilters")
	procTdhCleanupPayloadEventFilterDescriptor = modtdh.NewProc("TdhCleanupPayloadEventFilterDescriptor")
	procTdhCreatePayloadFilter                 = modtdh.NewProc("TdhCreatePayloadFilter")
	procTdhDeletePayloadFilter                 = modtdh.NewProc("TdhDeletePayloadFilter")
	procTdhEnumerateManifestProviderEvents     = modtdh.NewProc("TdhEnumerateManifestProviderEvents")
	procTdhEnumerateProviderFieldInformation   = modtdh.NewProc("TdhEnumerateProviderFieldInformation")
	procTdhEnumerateProviders                  = modtdh.NewProc("TdhEnumerateProviders")
	procTdhFormatProperty                      = modtdh.NewProc("TdhFormatProperty")
	procTdhGetEventInformation                 = modtdh.NewProc("TdhGetEventInformation")
	procTdhGetEventMapInformation              = modtdh.NewProc("TdhGetEventMapInformation")
	procTdhGetProperty                         = modtdh.NewProc("TdhGetProperty")
	procTdhGetPropertySize                     = modtdh.NewProc("TdhGetPropertySize")
	procTdhQueryProviderFieldInformation       = modtdh.NewProc("TdhQueryProviderFieldInformation")
)

func controlTrace_64(sessionHandle uint64, instanceName *uint16, properties *eventTraceProperties, controlCode uint32) (ret error) {
	r0, _, _ := syscall.Syscall6(procControlTraceW.Addr(), 4, uintptr(sessionHandle), uintptr(unsafe.Pointer(instanceName)), uintptr(unsafe.Pointer(properties)), uintptr(controlCode), 0, 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func controlTrace_32(sessionHandleLower uint32, sessionHandleHigher uint32, instanceName *uint16, properties *eventTraceProperties, controlCode uint32) (ret error) {
	r0, _, _ := syscall.Syscall6(procControlTraceW.Addr(), 5, uintptr(sessionHandleLower), uintptr(sessionHandleHigher), uintptr(unsafe.Pointer(instanceName)), uintptr(unsafe.Pointer(properties)), uintptr(controlCode), 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func enableTraceEx2_32(sessionHandleLower uint32, sessionHandleHigher uint32, providerGuid *windows.GUID, controlCode uint32, level TraceLevel, matchAnyKeywordLower uint32, matchAnyKeywordHigher uint32, matchAllKeywordLower uint32, matchAllKeywordHigher uint32, timeout uint32, enableParameters *enableTraceParameters) (ret error) {
	r0, _, _ := syscall.Syscall12(procEnableTraceEx2.Addr(), 11, uintptr(sessionHandleLower), uintptr(sessionHandleHigher), uintptr(unsafe.Pointer(providerGuid)), uintptr(controlCode), uintptr(level), uintptr(matchAnyKeywordLower), uintptr(matchAnyKeywordHigher), uintptr(matchAllKeywordLower), uintptr(matchAllKeywordHigher), uintptr(timeout), uintptr(unsafe.Pointer(enableParameters)), 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func enableTraceEx2_64(sessionHandle uint64, providerGuid *windows.GUID, controlCode uint32, level TraceLevel, matchAnyKeyword uint64, matchAllKeyword uint64, timeout uint32, enableParameters *enableTraceParameters) (ret error) {
	r0, _, _ := syscall.Syscall9(procEnableTraceEx2.Addr(), 8, uintptr(sessionHandle), uintptr(unsafe.Pointer(providerGuid)), uintptr(controlCode), uintptr(level), uintptr(matchAnyKeyword), uintptr(matchAllKeyword), uintptr(timeout), uintptr(unsafe.Pointer(enableParameters)), 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func processTrace(handleArray *uint64, handleCount uint32, startTime *windows.Filetime, endTime *windows.Filetime) (ret error) {
	r0, _, _ := syscall.Syscall6(procProcessTrace.Addr(), 4, uintptr(unsafe.Pointer(handleArray)), uintptr(handleCount), uintptr(unsafe.Pointer(startTime)), uintptr(unsafe.Pointer(endTime)), 0, 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func startTrace(sessionHandle *uint64, sessionName *uint16, traceProperties unsafe.Pointer) (ret error) {
	r0, _, _ := syscall.Syscall(procStartTraceW.Addr(), 3, uintptr(unsafe.Pointer(sessionHandle)), uintptr(unsafe.Pointer(sessionName)), uintptr(traceProperties))
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func traceQueryInformation_32(sessionHandleLower uint32, sessionHandleHigher uint32, infoClass traceQueryInfoClass, buffer unsafe.Pointer, bufferSize uint32, returnLength *uint32) (ret error) {
	r0, _, _ := syscall.Syscall6(procTraceQueryInformation.Addr(), 6, uintptr(sessionHandleLower), uintptr(sessionHandleHigher), uintptr(infoClass), uintptr(buffer), uintptr(bufferSize), uintptr(unsafe.Pointer(returnLength)))
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func traceQueryInformation_64(sessionHandle uint64, infoClass traceQueryInfoClass, buffer unsafe.Pointer, bufferSize uint32, returnLength *uint32) (ret error) {
	r0, _, _ := syscall.Syscall6(procTraceQueryInformation.Addr(), 5, uintptr(sessionHandle), uintptr(infoClass), uintptr(buffer), uintptr(bufferSize), uintptr(unsafe.Pointer(returnLength)), 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func traceSetInformation_64(sessionHandle uint64, infoClass traceQueryInfoClass, buffer unsafe.Pointer, bufferSize uint32) (ret error) {
	r0, _, _ := syscall.Syscall6(procTraceSetInformation.Addr(), 4, uintptr(sessionHandle), uintptr(infoClass), uintptr(buffer), uintptr(bufferSize), 0, 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func traceSetInformation_32(sessionHandleLower uint32, sessionHandleHigher uint32, infoClass traceQueryInfoClass, buffer unsafe.Pointer, bufferSize uint32) (ret error) {
	r0, _, _ := syscall.Syscall6(procTraceSetInformation.Addr(), 5, uintptr(sessionHandleLower), uintptr(sessionHandleHigher), uintptr(infoClass), uintptr(buffer), uintptr(bufferSize), 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func aggregatePayloadFilters(payloadFilterCount uint32, payloadFilters *uintptr, eventMatchAllFlags *bool, filterDescriptor *eventFilterDescriptorC) (ret error) {
	var _p0 uint32
	if *eventMatchAllFlags {
		_p0 = 1
	}
	r0, _, _ := syscall.Syscall6(procTdhAggregatePayloadFilters.Addr(), 4, uintptr(payloadFilterCount), uintptr(unsafe.Pointer(payloadFilters)), uintptr(unsafe.Pointer(&_p0)), uintptr(unsafe.Pointer(filterDescriptor)), 0, 0)
	*eventMatchAllFlags = _p0 != 0
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func cleanupPayloadEventFilterDescriptor(filterDescriptor *eventFilterDescriptorC) (ret error) {
	r0, _, _ := syscall.Syscall(procTdhCleanupPayloadEventFilterDescriptor.Addr(), 1, uintptr(unsafe.Pointer(filterDescriptor)), 0, 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func createPayloadFilter(providerGuid *windows.GUID, descriptor *EventDescriptor, eventMatchAny bool, payloadPredicateCount uint32, payloadPredicates *payloadFilterPredicate, payloadFilter *uintptr) (ret error) {
	var _p0 uint32
	if eventMatchAny {
		_p0 = 1
	}
	r0, _, _ := syscall.Syscall6(procTdhCreatePayloadFilter.Addr(), 6, uintptr(unsafe.Pointer(providerGuid)), uintptr(unsafe.Pointer(descriptor)), uintptr(_p0), uintptr(payloadPredicateCount), uintptr(unsafe.Pointer(payloadPredicates)), uintptr(unsafe.Pointer(payloadFilter)))
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func deletePayloadFilter(payloadFilter *uintptr) (ret error) {
	r0, _, _ := syscall.Syscall(procTdhDeletePayloadFilter.Addr(), 1, uintptr(unsafe.Pointer(payloadFilter)), 0, 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func enumerateManifestProviderEvents(providerGuid *windows.GUID, buffer *providerEventInfo, bufferSize *uint32) (ret error) {
	r0, _, _ := syscall.Syscall(procTdhEnumerateManifestProviderEvents.Addr(), 3, uintptr(unsafe.Pointer(providerGuid)), uintptr(unsafe.Pointer(buffer)), uintptr(unsafe.Pointer(bufferSize)))
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func enumerateProviderFieldInformation(guid *windows.GUID, fieldType EventFieldType, buffer *providerFieldInfoArray, bufferSize *uint32) (err error) {
	r1, _, e1 := syscall.Syscall6(procTdhEnumerateProviderFieldInformation.Addr(), 4, uintptr(unsafe.Pointer(guid)), uintptr(fieldType), uintptr(unsafe.Pointer(buffer)), uintptr(unsafe.Pointer(bufferSize)), 0, 0)
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func enumerateProviders(buffer *providerEnumerationInfo, bufferSize *uint32) (ret error) {
	r0, _, _ := syscall.Syscall(procTdhEnumerateProviders.Addr(), 2, uintptr(unsafe.Pointer(buffer)), uintptr(unsafe.Pointer(bufferSize)), 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func tdhFormatProperty(event *eventRecordC, mapInfo *uint8, pointerSize uint32, inType uint16, outType uint16, propertyLength uint16, userDataLength uint16, userData *uint8, bufferSize *uint32, buffer *uint8, userDataConsumed *uint16) (ret error) {
	r0, _, _ := syscall.Syscall12(procTdhFormatProperty.Addr(), 11, uintptr(unsafe.Pointer(event)), uintptr(unsafe.Pointer(mapInfo)), uintptr(pointerSize), uintptr(inType), uintptr(outType), uintptr(propertyLength), uintptr(userDataLength), uintptr(unsafe.Pointer(userData)), uintptr(unsafe.Pointer(bufferSize)), uintptr(unsafe.Pointer(buffer)), uintptr(unsafe.Pointer(userDataConsumed)), 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func tdhGetEventInformation(event *eventRecordC, contextCount uint32, context unsafe.Pointer, buffer *uint8, bufferSize *uint32) (ret error) {
	r0, _, _ := syscall.Syscall6(procTdhGetEventInformation.Addr(), 5, uintptr(unsafe.Pointer(event)), uintptr(contextCount), uintptr(context), uintptr(unsafe.Pointer(buffer)), uintptr(unsafe.Pointer(bufferSize)), 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func tdhGetEventMapInformation(event *eventRecordC, mapName *uint16, buffer *uint8, bufferSize *uint32) (ret error) {
	r0, _, _ := syscall.Syscall6(procTdhGetEventMapInformation.Addr(), 4, uintptr(unsafe.Pointer(event)), uintptr(unsafe.Pointer(mapName)), uintptr(unsafe.Pointer(buffer)), uintptr(unsafe.Pointer(bufferSize)), 0, 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func tdhGetProperty(event *eventRecordC, contextCount uint32, context unsafe.Pointer, propertyDataCount uint32, propertyData *propertyDataDescriptor, bufferSize uint32, buffer unsafe.Pointer) (ret error) {
	r0, _, _ := syscall.Syscall9(procTdhGetProperty.Addr(), 7, uintptr(unsafe.Pointer(event)), uintptr(contextCount), uintptr(context), uintptr(propertyDataCount), uintptr(unsafe.Pointer(propertyData)), uintptr(bufferSize), uintptr(buffer), 0, 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func tdhGetPropertySize(event *eventRecordC, contextCount uint32, context unsafe.Pointer, propertyDataCount uint32, propertyData *propertyDataDescriptor, propertySize *uint32) (ret error) {
	r0, _, _ := syscall.Syscall6(procTdhGetPropertySize.Addr(), 6, uintptr(unsafe.Pointer(event)), uintptr(contextCount), uintptr(context), uintptr(propertyDataCount), uintptr(unsafe.Pointer(propertyData)), uintptr(unsafe.Pointer(propertySize)))
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func queryProviderFieldInformation_64(guid *windows.GUID, eventFieldValue uint64, eventFieldType EventFieldType, buffer *providerFieldInfoArray, bufferSize *uint32) (ret error) {
	r0, _, _ := syscall.Syscall6(procTdhQueryProviderFieldInformation.Addr(), 5, uintptr(unsafe.Pointer(guid)), uintptr(eventFieldValue), uintptr(eventFieldType), uintptr(unsafe.Pointer(buffer)), uintptr(unsafe.Pointer(bufferSize)), 0)
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func queryProviderFieldInformation_32(guid *windows.GUID, eventFieldValueLower uint32, eventFieldValueHigher uint32, eventFieldType EventFieldType, buffer *providerFieldInfoArray, bufferSize *uint32) (ret error) {
	r0, _, _ := syscall.Syscall6(procTdhQueryProviderFieldInformation.Addr(), 6, uintptr(unsafe.Pointer(guid)), uintptr(eventFieldValueLower), uintptr(eventFieldValueHigher), uintptr(eventFieldType), uintptr(unsafe.Pointer(buffer)), uintptr(unsafe.Pointer(bufferSize)))
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}
